#!/bin/sh

TOOLCHAIN=/tmp/build/xtensa-lx106-elf

# Download some tarballs to speed up the build
mkdir tarballs
cd tarballs
wget "ftp://gcc.gnu.org/pub/gcc/infrastructure/isl-0.14.tar.bz2"

# Configure and install crosstool-NG 
cd ../crosstool-NG
./bootstrap
./configure --prefix=`pwd`
make
make install

# Configure and build the target toolchain
./ct-ng xtensa-lx106-elf
cat ../crosstool-config-overrides >> .config
echo "CT_PREFIX_DIR=$TOOLCHAIN" >> .config
./ct-ng build

# Configure and build the lx106 HAL
cd ../lx106-hal
autoreconf -i
PATH="$TOOLCHAIN/bin:$PATH" ./configure --host=xtensa-lx106-elf --prefix=$TOOLCHAIN/xtensa-lx106-elf/sysroot/usr
PATH="$TOOLCHAIN/bin:$PATH" make
PATH="$TOOLCHAIN/bin:$PATH" make install

