#!/bin/sh

TOOLCHAIN_DIR=$1
CTNG_VERSION="1.23.0"
ctng_dir="crosstool-ng-${CTNG_VERSION}"
ctng_filename="${ctng_dir}.tar.xz"
ctng_url="http://crosstool-ng.org/download/crosstool-ng/${ctng_filename}"

# Download and extract crosstool-NG and Xtensa overlay
wget $ctng_url
tar xf $ctng_filename
cd $ctng_dir
# Extract the overlay
mkdir overlays
gzip -d -c ../overlays/xtensa_lx106.tar.gz > overlays/xtensa_lx106.tar
# Copy the config in place
cp -r ../ctng-config samples/xtensa-lx106-elf

# Configure and build crosstool-NG
./configure --enable-local
make

# Configure and build the target toolchain
./ct-ng xtensa-lx106-elf
echo "CT_PREFIX_DIR=$TOOLCHAIN_DIR" >> .config
./ct-ng build

# Configure and build the lx106 HAL
PATH=$TOOLCHAIN_DIR/bin:$PATH
cd ../lx106-hal
autoreconf -i
./configure --host=xtensa-lx106-elf --prefix=$TOOLCHAIN_DIR/xtensa-lx106-elf
make
make install
